### ISSUE TITLE
Corrigez un bug dans la gestion des prolongations de prêt (par le client)

### ISSUE THREAD

**Issue by Deyine** [RomainDavidS/ManagementLibraryV2#2]
Nous avons découvert un bug de la gestion des prolongations de prêt. En effet, un usager peut prolonger un prêt après la date butoir. Il ne doit pas être possible pour l’usager de prolonger un prêt si la date de fin de prêt est dépassée.

La correction de cette anomalie est urgente car elle nous pose de gros problèmes de gestion. Actuellement beaucoup trop de personnes attendent le mail de rappel pour prolonger leur prêt. Cela entraîne la plainte de certains usagers à qui nous avions communiqué une date de retour et qui se déplacent en bibliothèque pour rien car le prêt a été prolongé a posteriori.

Je vous demande de livrer une nouvelle version de l’application au plus vite afin de corriger ce bug mais sans inclure nos autres demandes en cours. Nous souhaiterions pouvoir mettre en production rapidement sans avoir à faire de recette sur les autres évolutions demandées.

**Comment by RomainDavidS** [comment]
Bonjour, 
Afin d'apporter une réponse rapidement nous aimerions une confirmation sur la date de fin de prêt est dépassée.
Considérez-vous que même si l usager n'a jamais fait de renouvellement il n'a pas la possibilité de prolonger de prêt si la date de fin de prêts est dépassé ?
C'est une règle de gestion de gestion qui n'a pas été mise en place lors la première livraison.
Voilà ce que nous proposons de rajouter comme règle de gestion : 
Un usager pourra faire un renouvellement afin la fin de prêt dans le cas où il n'a déjà pas fait de renouvellement. Donc même si l'usager n'a jamais fait de renouvellement si la date de fin de prêt est dépassé il n'aura pas la possibilité de prolonger son emprunt. 
Pouvez-vous me confirmer que cette nouvelle règle de gestion vous convienne afin que nous l'appliquions au plus vite.
Merci

**Comment by RomainDavidS** [comment]
Bonjour,
Nous venons de mettre en ligne une nouvelle version v1.0.2 apportant la mise à jour de la règle de gestion concernant le renouvellement d'emprunt
